# Generated by Django 2.0 on 2020-05-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TasksManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Phone',
            new_name='phone',
        ),
    ]
